### ISSUE TITLE
Missing ' in roxygen 

### ISSUE THREAD

**Issue by karlvurdst** [CollinErickson/GauPro#1]
Was just reading your code to get inspiration on writing R6 class, and noticed this missing `'`. Not critical at all. 

https://github.com/CollinErickson/GauPro/blob/d2951e7400515c1251711074af3243e4936893a7/R/GauPro_base.R#L9

**Comment by CollinErickson** [comment]
Sorry for not seeing this until now. GitHub never sent me emails for issues or pull requests, which I just found out recently. I think I may have removed that `'`  on purpose so it wouldn't show up, but I didn't want to delete it in case I changed my mind later? I'm not sure, but I don't encourage anyone to use that function anymore, so I'm going to leave it as is. Thanks for your contribution!
